package com.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * TGoods generated by MyEclipse Persistence Tools
 */

public class GoodRank implements java.io.Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String goodName;
	private String goodImageUrl;
	private BigDecimal goodPrice;
	private Integer goodId;
	private Integer saleAmount;
	private Date createDate;
	private Date modifyDate;
	private Boolean deleted;
	private String goodNameBrief;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getGoodName() {
		return goodName;
	}
	public void setGoodName(String goodName) {
		this.goodName = goodName;
	}
	public String getGoodImageUrl() {
		return goodImageUrl;
	}
	public void setGoodImageUrl(String goodImageUrl) {
		this.goodImageUrl = goodImageUrl;
	}
	public BigDecimal getGoodPrice() {
		return goodPrice;
	}
	public void setGoodPrice(BigDecimal goodPrice) {
		this.goodPrice = goodPrice;
	}
	public Integer getGoodId() {
		return goodId;
	}
	public void setGoodId(Integer goodId) {
		this.goodId = goodId;
	}
	public Integer getSaleAmount() {
		return saleAmount;
	}
	public void setSaleAmount(Integer saleAmount) {
		this.saleAmount = saleAmount;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public Date getModifyDate() {
		return modifyDate;
	}
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
	public Boolean getDeleted() {
		return deleted;
	}
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}
	public String getGoodNameBrief() {
		goodNameBrief = goodName.substring(0, 2);
		return goodNameBrief;
	}
	public void setGoodNameBrief(String goodNameBrief) {
		this.goodNameBrief = goodNameBrief;
	}
}